name: "build"

on:
  push:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'build/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'build/**'

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  ALIYUN_DOCKERHUB: ${{ secrets.ALIYUN_DOCKERHUB }}
  ALIYUN_DOCKERHUB_USERNAME: ${{ secrets.ALIYUN_DOCKERHUB_USERNAME }}
  ALIYUN_DOCKERHUB_TOKEN: ${{ secrets.ALIYUN_DOCKERHUB_TOKEN }}

jobs:
  arm64:
    runs-on: ubuntu-18.04
    name: Build on ubuntu-18.04 arm64
    steps:
      # checkout source code
      - uses: actions/checkout@v2

      # login docker hub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{env.DOCKERHUB_USERNAME}}
          password: ${{env.DOCKERHUB_TOKEN}}

      # arm64    
      - uses: uraimo/run-on-arch-action@v2.3.0
        name: use arm64
        id: runcmd
        with:
          arch: aarch64 # cpu架构
          distro: ubuntu18.04 # linux发行版
          shell: /bin/bash # 执行的shell
          githubToken: ${{ github.token }} # Not required, but speeds up builds by storing container images in a GitHub package registry.
          # Set an output parameter `uname` for use in subsequent steps
          run: |
            uname -a
            echo ::set-output name=uname::$(uname -a)
      
      # build
      - name: build
        run: ./build.ps1
        shell: pwsh
        working-directory: ./build

  # # push to docker hub
  # build-and-push-docker-hub:

  #   # set os
  #   runs-on: ubuntu-latest

  #   steps:
  #     # checkout source code
  #     - uses: actions/checkout@v2

  #     # login docker hub
  #     - name: Login to DockerHub
  #       uses: docker/login-action@v1
  #       with:
  #         username: ${{env.DOCKERHUB_USERNAME}}
  #         password: ${{env.DOCKERHUB_TOKEN}}

  #     # build and push all images
  #     - name: build and push images
  #       run: ./build_and_push_imgs.ps1
  #       shell: pwsh
  #       working-directory: ./build

  # # push to aliyun
  # push-aliyu:

  #   # set os
  #   runs-on: ubuntu-latest
  #   needs: [ build-and-push-docker-hub ]
  #   steps:
  #     # checkout source code
  #     - uses: actions/checkout@v2

  #     # login docker hub
  #     - name: Login to DockerHub
  #       uses: docker/login-action@v1
  #       with:
  #         registry: ${{env.ALIYUN_DOCKERHUB}}
  #         username: ${{env.ALIYUN_DOCKERHUB_USERNAME}}
  #         password: ${{env.ALIYUN_DOCKERHUB_TOKEN}}

  #     # build and push all images
  #     - name: build and push images
  #       run: ./build/push_imgs_aliyun.ps1
  #       shell: pwsh
  #       working-directory: ./
