name: "build"

on:
  push:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'build/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'build/**'

env:
  DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  ALIYUN_DOCKERHUB: ${{ vars.ALIYUN_DOCKERHUB }}
  ALIYUN_DOCKERHUB_USERNAME: ${{ vars.ALIYUN_DOCKERHUB_USERNAME }}
  ALIYUN_DOCKERHUB_TOKEN: ${{ secrets.ALIYUN_DOCKERHUB_TOKEN }}

jobs:
  sync-hub:
    runs-on: ubuntu-20.04
    name: Sync to DockerHub
    steps:
      # checkout source code
      - uses: actions/checkout@v2

      # login docker hub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{env.DOCKERHUB_USERNAME}}
          password: ${{env.DOCKERHUB_TOKEN}}

      # build
      - name: build
        shell: pwsh
        working-directory: ./build
        run: ./build-sync.ps1

  sync-aliyun:
    runs-on: ubuntu-20.04
    name: Sync to Aliyun
    steps:
      # checkout source code
      - uses: actions/checkout@v2

      # login docker hub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ${{env.ALIYUN_DOCKERHUB}}
          username: ${{env.ALIYUN_DOCKERHUB_USERNAME}}
          password: ${{env.ALIYUN_DOCKERHUB_TOKEN}}

      # build
      - name: build
        shell: pwsh
        working-directory: ./build
        run: ./build-sync.ps1 $True

  sync-hub-win:
    runs-on: ubuntu-20.04
    name: Sync to DockerHub (Win)
    steps:
      # checkout source code
      - uses: actions/checkout@v2

      # login docker hub
      - name: Login to DockerHub
        uses: azure/docker-login@v1
        with:
          username: ${{env.DOCKERHUB_USERNAME}}
          password: ${{env.DOCKERHUB_TOKEN}}

      # build
      - name: build
        shell: pwsh
        working-directory: ./build
        run: ./build-sync.ps1

  sync-aliyun-win:
    runs-on: ubuntu-20.04
    name: Sync to Aliyun (Win)
    steps:
      # checkout source code
      - uses: actions/checkout@v2

      # login docker hub
      - name: Login to DockerHub
        uses: azure/docker-login@v1
        with:
          login-server: ${{env.ALIYUN_DOCKERHUB}}
          username: ${{env.ALIYUN_DOCKERHUB_USERNAME}}
          password: ${{env.ALIYUN_DOCKERHUB_TOKEN}}

      # build
      - name: build
        shell: pwsh
        working-directory: ./build
        run: ./build-sync.ps1 $True